#!/bin/sh

touch U.dat
touch D.dat

set vals = 200 205 210 215 220 225 230 235 240 245 250
#90 100 110 120 130 140 150 160 170 180 200 210 220 230; 

for val in 180 190 195 200  
do
  echo $val
  sed 's/@TT/'$val'/' input.in > input # sed è una funzione per sostituire testo
  ./md < input
  cp coord.xyz coords_$val.xyz
  cp av.dat av_$val.dat
  cp g.dat g_$val.dat
  cp R2.dat R2_$val.dat
  awk '{if(NR==1){print '"$val"', $4, $6}}' av_$val.dat >> U.dat
  awk '{if(NR==3){print '"$val"', $2}}' av_$val.dat >> D.dat
done

