#!/bin/sh

touch data/U.dat
touch data/D.dat

set vals = 200 205 210 215 220 225 230 235 240 245 250
#90 100 110 120 130 140 150 160 170 180 200 210 220 230; 

for val in 180 190 195 200  
do
  echo $val
  sed 's/@TT/'$val'/' input.in > input # sed è una funzione per sostituire testo
  ./md < input
  cp data/coord.xyz data/coords_$val.xyz
  cp data/av.dat data/av_$val.dat
  cp data/g.dat data/g_$val.dat
  cp data/R2.dat data/R2_$val.dat
  awk '{if(NR==1){print '"$val"', $4, $6}}' data/av_$val.dat >> data/U.dat
  awk '{if(NR==3){print '"$val"', $2}}' data/av_$val.dat >> data/D.dat
done

